### ISSUE TITLE
[HW3] describe 후 위에 있는 it이 아래의 it에 영향을 미칩니다. 해결 방안이 있을까요?

### ISSUE THREAD

**Issue by creeper00** [swsnu/swppfall2020#144]
![스크린샷, 2020-10-14 20-32-30](https://user-images.githubusercontent.com/43807159/95983358-7228f900-0e5c-11eb-893e-43c02183d754.png)
describe 후 it 을 사용해서 각각의 test를 처리하려 하는데 
위에 it이 아래의 it에 영향을 미쳐 제대로 테스트를 할 수 없습니다.
예를들어 사진에서 it의 위치를 바꾸면 test결과가 바뀌고,
logout을 테스트 한후에 create-article-button이 없다고 나와서 제대로 테스트가 안됩니다.
무엇이 문제 일까요?

![스크린샷, 2020-10-14 20-43-50](https://user-images.githubusercontent.com/43807159/95984348-0051af00-0e5e-11eb-8c11-51d38241b833.png)

위에 보신 것처럼 debug를 찍어봤을 때 싹 사라져있습니다.

**Comment by creeper00** [comment]
확인 결과 Redirect를 쓸 시 나타나는 문제인것 같습니다. history로 바꾸니 해결되었습니다.

**Comment by creeper00** [comment]
그런데 Redirect가 없는 곳에서도 같은 문제가 발생하는데 영문을 모르겠네요

**Comment by gina7484** [comment]
저도 비슷한 상황이었었는데 위에서 Redirect되어서 아래에 영향을 주는 문제였습니다.
문제가 일어나는 부분에서 history를 출력해서 path를 확인해보세요.
이를 막으려면 redirect되지 않게 mock하시면 될 것 같습니다.

**Comment by kooyunmo** [comment]
mocking이 제대로 되지 않은 것으로 보입니다. Provider에 들어가는 store가 제대로 mocking되었는지도 한번 확인 바랍니다.

**Comment by creeper00** [comment]
넵 ! 감사합니다!
