### ISSUE TITLE
[팀원모집] 팀원 구합니다. 

### ISSUE THREAD

**Issue by chullino** [swsnu/swppfall2020#2]
🚀 🚀 🚀   팀원 구합니다! 🚀 🚀 🚀 

안녕하세요, 수강생 최린범입니다.

언어(Python, JS), 프레임웍(Django, React), 및 AWS 서비스 경험은 있으나 잘 하지는 못합니다.
특히나, ML로 서비스를 짜야하는, 강력한 로드의 소개원실 수업을 무리없이 따라갈만큼은 아닙니다.

어느 팀에 속하게 되어도 누가 되지 않고 성실한 팀원이 되도록 노력하겠습니다.
코드리뷰에 힘쓰도록 하겠습니다.

👏  자리가 남아있는 팀이 있다면, 다른 분들도 확인하실 수 있도록 **해당 팀 인원수**와 함께, 커멘트 달아주시면 감사드리겠습니다.
👏 저처럼 독강생이라 바닥부터 팀을 구성하셔야 하는 분들도 환영하오니, 커멘트 달아주시면 감사드리겠습니다.

조교님께서 말씀하신대로, 팀원 모집 완료 후에는 Issue close 하도록 하겠습니다.

즐거운 소개원실 수업이 되길 바랍니다.
감사합니다!

**Comment by jiyewise** [comment]
안녕하세요, 소개원실 수강생 이지예입니다. 저희 팀은 저 포함 현재 3명이어서 한명의 팀원을 모집하고 있습니다! 팀프로젝트가 본격적으로 시작되는 10월부터 주기적으로 팀원들끼리 오프라인으로 만나서 같이 논의하고 개발할 계획이니 참여하실 수 있는 분이면 좋겠습니다! (코로나 사태가 심각해지면 온라인으로 전환할 계획입니다) 관심 있으시면 카톡아이디 jkaylpn으로 연락주시면 감사하겠습니다 ㅎㅎ

**Comment by ddongminstar** [comment]
안녕하세요. 수강생 김동민입니다. 현재 컴공생 2명으로 팀을 구성했고, 또 2명을 추가로 모집하려고 합니다. 

성실하고 꾸준하게 개발을 진행하며 같이 성장할 수 있으면 좋겠습니다.

관심있으시면 카톡 아이디 dmk98로 연락주시면 감사하겠습니다.

**Comment by jiyewise** [comment]
> 안녕하세요, 소개원실 수강생 이지예입니다. 저희 팀은 저 포함 현재 3명이어서 한명의 팀원을 모집하고 있습니다! 팀프로젝트가 본격적으로 시작되는 10월부터 주기적으로 팀원들끼리 오프라인으로 만나서 같이 논의하고 개발할 계획이니 참여하실 수 있는 분이면 좋겠습니다! (코로나 사태가 심각해지면 온라인으로 전환할 계획입니다) 관심 있으시면 카톡아이디 jkaylpn으로 연락주시면 감사하겠습니다 ㅎㅎ

*마감되었습니다!

**Comment by chullino** [comment]
모집 완료되었고, close하겠습니다.
답변 주셔서 정말 감사드립니다!
🙇 🙇 🙇
