### ISSUE TITLE
[Travis] 버그 및 디버깅 방법 관련 질문입니다.

### ISSUE THREAD

**Issue by chullino** [swsnu/swppfall2020#206]
안녕하세요 팀 16 최린범입니다.
날씨도 쌀쌀해지는데 따뜻하게 지내시는지 모르겠습니다.

다름 아니라, 트라비스 관련해서 하나의 문제가 발생해서 문의드리고자 이슈를 작성하게 되었습니다. 전에는 깃헙에 푸시를 날리면 트라비스가 잘 돌아갔는데, 지금은 아무 이유없이 잘 돌아가지 않아서 문의 드리게 되었습니다. 트라비스가 (1) 코드 데이터를 받고, (2) 큐에 넣었다가, (3) 빌드 스타트를 하는 식인데, (1)조차 시작을 안하는 상황입니다. 

***

저희 팀에서 수행한 가장 최근 push는 4일 전입니다. 푸시를 날리니, 자동적으로 트라비스가 돌았습니다.
<img width="953" alt="스크린샷 2020-11-06 오전 11 15 15" src="https://user-images.githubusercontent.com/40787830/98318172-65459280-2021-11eb-84e3-c6c95f73caa8.png">

하지만, 지금은 푸시를 날리거나, 풀리퀘를 날려도 트라비스가 도는 것이 확인이 되지 않습니다. 그래서 저희는 네 가지 디버깅을 시행했습니다. 

***

**(1) travis.yml파일에 문법적 오류가 있는지.**
혹시 저희가 잘못한 것이 없나 확인해보려고 travis.yml 파일을 `travis lint`로 체크해 보았는데 워닝 및 alert는 있어도 에러가 날 수 있는 문제는 찾지 못했습니다.[워닝 및 얼러트는 이전에도 있었던 것들이었습니다.]

**(2) 레포 travis 관련 변경사항을 지난 4일 사이에 변경한 적이 있는지.**
팀원들 중에는 따로 없었습니다.

**(3) 그럼에도 혹시 모를 변경사항이 생겼을지도 모르니 4일 전 브랜치를 고스란히 받아와서 푸시를 날려봤는지.** 
위에 있는 브랜치로 변경없이 똑같이 푸시를 날려도 트라비스에서 아무런 반응이 없습니다. 이전에는 푸시 및 풀리퀘마다 트라비스가 돌았는데 깃헙 자체에서 뭔가 문제가 있는지 수행이 되지 않습니다. 깃헙에서 트라비스로 트리거를 날리지 못하는 것인가 싶기도 합니다.

**(4)  com, org 문제를 체크해보았는지.**
travis/settings 설정을 모두 똑같이 해보았지만 org/com 모두 에서도 트라비스가 도는 것이 확인되지 않았습니다. 하지만, 디버깅 과정 중에서  다음의 힌트를 얻을 수 있었습니다.

travis-ci.com에서 인테그레이션 정보를 확인해보니, 저희 팀이 인테그레이션에서 제외되어 있었습니다.
<img width="1162" alt="스크린샷 2020-11-06 오후 12 14 07" src="https://user-images.githubusercontent.com/40787830/98321978-b8234800-2029-11eb-8831-9646eeb6f9e6.png">
위 이미지에서 확인하실 수 있듯이, 저희 팀(16)이 인테그레이션 목록에서 제외되었습니다.

그래서 인테그레이션을 추가하려고 보니, 오너 권한을 가진 분만 추가할 수 있는 것으로 나왔습니다.
<img width="1193" alt="스크린샷 2020-11-06 오후 12 14 20" src="https://user-images.githubusercontent.com/40787830/98322085-f0c32180-2029-11eb-9a73-6ae735c5e545.png">

저희 팀을 인테그레이션 목록에 추가해주시면 다시 디버깅 해보도록 하겠습니다.

***

이 외에 혹시 더 디버깅해 볼 수 있는 방안이 있을지 궁금합니다. swsnu 트라비스 로그를 보면 다른 팀에서는 빌드가 잘 진행이 되는 듯 싶은데(7시간 정도 빌드가 잘 진행되는 듯 싶어서요), 저희 팀만 이런가 싶기도 해서 조금 혼란스러운 상황입니다.

모쪼록 즐거운 하루 되시면 좋겠습니다!
감사합니다.

**Comment by kooyunmo** [comment]
마지막 스크린샷은 manage repositories on GitHub 버튼을 눌렀을 때의 화면인가요? 지금 이상하게 travis-ci.com에서는 이상하게 팀 10과 16만 추가가 되지 않는 상황입니다.

![image](https://user-images.githubusercontent.com/17061663/98330034-e8c0ad00-203c-11eb-8a6b-a1aae98f4ee1.png)
 
travis-ci.org를 사용해야 할 것 같은데 레포 setting의 Webhook에서 travis-ci.com은 삭제하고 travis-ci.org로 설정을 해야할 것 같습니다.

![image](https://user-images.githubusercontent.com/17061663/98330112-0beb5c80-203d-11eb-8e7d-97cc44af96b9.png)

한 번 시도해보시고 잘 안되면 댓글 달아주세요. 제가 직접 추가해보겠습니다.

**Comment by chullino** [comment]
A request to swsnu already exists, cancel before submitting a new one or wait for an administrator to respond. 라고 나오는데 혹시 관련 메일이나 해당 리퀘스트 확인해주시면 감사드리겠습니다!

<img width="1184" alt="스크린샷 2020-11-06 오후 2 44 06" src="https://user-images.githubusercontent.com/40787830/98330811-91bbd780-203e-11eb-8676-4cb25b188895.png">

**Comment by kooyunmo** [comment]
![image](https://user-images.githubusercontent.com/17061663/98331397-d3994d80-203f-11eb-9629-0af6234579ec.png)

리퀘스트를 수락했는데 여전히 ci.com에서 보이지 않는 것 같습니다. org를 쓰는 편이 나아 보이는데 어떻게 생각하시나요

**Comment by chullino** [comment]
네 그러면 그렇게 하도록 하겠습니다.  sonarcloud도 working하는 것까지 확인 되어서 required badges도 모두 문제없이 달아둘 수 있을 듯 싶습니다.

**Comment by kooyunmo** [comment]
네 추후에도 문제가 있으면 세팅 도와드리도록 하겠습니다. 감사합니다.

**Comment by chullino** [comment]
네! 이슈는 닫아두도록 하겠습니다!
