### ISSUE TITLE
팀원 구합니다!

### ISSUE THREAD

**Issue by qwerty98765** [swsnu/swppfall2020#32]
안녕하세요! 소개원실 수강생 맹재우, 조승우, 구자운입니다.

저희와 함께할 팀원을 구합니다!

저희는 컴퓨터공학 복/부전생들이고 아직 배울 점이 많지만 React나 Django 등 웹에 대해 한번씩은 경험이 있습니다.

웹이나 디자인을 아시는 분이라면 더욱 좋겠지만 한 학기동안 즐겁게 프로젝트를 함께 하실 분이 있다면 언제든지 qwerty98765@snu.ac.kr 로 연락주시면 감사하겠습니다!

**Comment by hy00nc** [comment]
안녕하세요, 아직 팀원 모집 중이시라면 현재 수강인원 상 3인조로 편성이 되어야 할 거 같습니다.
혹시 추가 팀원을 구하셨다면 다른 팀으로 배정되어야 할 수도 있으니 이메일 부탁드립니다.
