### ISSUE TITLE
팀을 구합니다.

### ISSUE THREAD

**Issue by wafflejuice** [swsnu/swppfall2020#43]
안녕하세요. 컴퓨터공학부 15학번 정호근입니다.
늦게나마 팀을 구합니다.

본 수업과 관련해서는
- 전공 수업을 들으면서 python을 다뤄봤습니다.
- HTML과 SQL을 사용해 간단한 신청 사이트를 만들어봤습니다.
- 로또 번호를 크롤해오는 python 프로그램을 만들어봤습니다.
- 서울에서 모이는 오프라인 회의에 참석할 수 있습니다.

위에서 언급한 건 개인적으로 수행한 간단한 프로젝트였고, 대단한 능력을 갖추고 있지는 않지만
도중에 그만두지 않고 열심히 참여하고 싶습니다.

핸드폰 번호 : 010-9340-6636

**Comment by chullino** [comment]
팀에 참여해주셔서 감사드립니다. 이 이슈는 닫으셔도 괜찮을 듯 싶습니다!
