### ISSUE TITLE
추가 인원을 모집할 팀을 찾습니다

### ISSUE THREAD

**Issue by hy00nc** [swsnu/swppfall2020#46]
안녕하세요, 팀 결성 관련 공지드립니다.

본래 4인조 팀이 원칙이지만 두 팀에 한해서 추가인원을 모집할 수 있도록 하려고 합니다.
컴퓨터공학부 송찬석, ~~정호근~~ 학생이 합류할 팀을 모집하니 본 이슈에 comment 남겨주시면 이메일 드리도록 하겠습니다.
다음 주가 Proposal 마감이니만큼 최대한 빨리 팀 내 논의를 거쳐 comment 남겨주시면 감사하겠습니다.

**Comment by hy00nc** [comment]
참고로 프로젝트가 진행 될 수록 작업해야 할 문서 및 코드가 방대해지므로 인원 추가는 프로젝트 진행에 큰 메리트이니 적극 검토 부탁드립니다 :)

**Comment by chullino** [comment]
원하시는 한 분을 저희팀으로 모시고 싶습니다! 권순빈, 김동민, 김경환, 최린범 팀입니다. 이메일은 preetydragonov@snu.ac.kr로 보내주시면 감사드리겠습니다! 팀 프로젝트 마일스톤을 간단히 공유드리자면, 코딩 습관 health check 할 수 있는 앱을 만들 예정입니다.

**Comment by hy00nc** [comment]
송찬석 학생이 합류할 한 팀 모집합니다!

**Comment by SPICYJO** [comment]
안녕하세요! 구자운, 맹재우, 조승우 팀입니다. 수업시간에 팀원을 구하여서 4인팀을 구성하게 되었으나 그 분께서 오늘 드랍하기로 결정을 하셔서 현재 3인인 상태입니다. 송찬석 님께서 아직 다른 팀에 속하지 않은 상태라면 저희 팀으로 모시고 싶습니다! 이메일은 sjosjo1204@gmail.com으로 보내주시면 됩니다!

**Comment by SPICYJO** [comment]
송찬석 님께서 저희 팀에 합류하였습니다!
