### ISSUE TITLE
[HW3] button

### ISSUE THREAD

**Issue by ddongminstar** [swsnu/swppfall2020#60]
Each user should be able to update or delete articles and comments only which they have created.
라고 하셨는데, 이것은 그러면 backend가 아니라 front에서 확인하는 건가요?

그렇다면 
When a user hits confirm-edit-article-button, the user should be redirected to the article detail page (articles/:id) and the edited title and contents should be saved. Any comment for the article should not be modified or deleted by this process.

When a user hit the delete-article-button, the user should be redirected to the article list page (articles/) and the article should be deleted without any alert.

과 같은 경우들에서 redirection을 수행하고, 해당 정보를 update하라고 하셨는데, 그렇다면 다른 user의 article이나 comment에 대해서 버튼을 클릭하면 어떤 작업을 해야 하나요?

Button을 disable하거나, 권한이 없다고 alert를 띄우거나, 작업 없이 redirect하거나, redirect 없이 아무것도 안하거나 고민하다가 질문 드립니다.

감사합니다!

**Comment by kooyunmo** [comment]
- 이번 과제에서 백엔드는 직접 조작하지 않습니다. 저희가 제공한 mocking된 서버를 그대로 사용하면 됩ㄴ다. 따라서 user id 체크도 프론트엔드에서 하시면 됩니다.

- article detail page 설명에 나와있는 것과 마찬가지로 다른 user의 article이나 comment에 대해서는 버튼이 보이지 않아야 합니다. 보이지 않기 때문에 클릭이 불가능합니다.

> These buttons must be visible for the author only.

**Comment by ddongminstar** [comment]
Article edit page (/articles/:id/edit)

When a user hits confirm-edit-article-button, the user should be redirected to the article detail page (articles/:id) and the edited title and contents should be saved. Any comment for the article should not be modified or deleted by this process.

에서 제가 이해한게 맞다면 http://localhost:3000/articles/{article_id}/edit url을 입력하는 것으로 접속이 가능한거 같습니다. 그렇다면 edit 페이지에서 해당 user의 id가 article의 author_id와 일치 여부를 체크해야 할까요? 아니면 다른 user의 article에 대한 접속 시도를 어떻게 처리하면 좋을까요?

답변해 주셔서 감사합니다!

**Comment by kooyunmo** [comment]
주소창에 직접 url을 쳐서 페이지 이동을 하는 케이스는 다음 두 가지에 대해서만 테스트할 예정입니다.

1. 로그인 후에 `/login` 페이지로 강제로 돌아갔을 때 `/articles` 페이지로 오는지
2. 로그인 전에 다른 페이지 주소를 입력했을 때 그대로 `/login`페이지에 있는지

로그인 뒤에는 오직 버튼들을 통해서만 페이지를 이동한다고 가정을 하시면 됩니다. 즉, 말씀하신 것과 같이 직접 `articles/1/edit`을 주소창에 쳐서 페이지 이동하는 케이스는 고려하지 않으셔도 됩니다. hw3 설명에 있는 [스토리보드](https://github.com/swsnu/swppfall2020/tree/master/hw3#features)에 있는 페이지 이동만 잘 지원되면 됩니다.

**Comment by ddongminstar** [comment]
네 감사합니다!
