### ISSUE TITLE
[HW3] 윈도우 환경에서 npm run backend 커맨드 오류 수정법 관련

### ISSUE THREAD

**Issue by promet99** [swsnu/swppfall2020#68]
안녕하세요,
HW3의 readme에서 window 사용자를 위한 npm run backend의 코맨드가 제 윈도우 환경에서는 작동하지 않더라구요, 
그래서 ￦￦를 \\로 바꾸니 해결되었습니다! 
(\나 ￦나 /로 바꾸는건 전부 안되는데, 불가사의한 일입니다!)
아마 ￦랑 \가 혼용되는 글꼴 등등이 원인이 아닌가 싶습니다.

아래는 수정된 코드입니다.
`"backend": "copy /y api\\db.json api\\_db.json && json-server --watch api\\_db.json --routes api\\routes.json --port 8000"`

윈도우에서 과제를 하시는 다른 학우분들께 도움이 될까 하여 올려봅니다.

P.S. 불철주야 답변해주시는 조교님들 감사합니다.

**Comment by kooyunmo** [comment]
좋은 정보 공유 감사합니다. 다른 수강생들에게도 도움이 될 것 같습니다!
