### ISSUE TITLE
[HW3] Redux 제외 다른 global state management 라이브러리 사용 여부 질문

### ISSUE THREAD

**Issue by promet99** [swsnu/swppfall2020#73]
Redux를 제외한, RecoilJs나 Mobx 와 같은 global state management 라이브러리를 사용해도 괜찮은지 궁금합니다.

감사합니다.

**Comment by kooyunmo** [comment]
이번 과제의 목적이 React & Redux를 통한 구현을 연습하는 것이고, 형평성 문제 등을 고려하여 말씀하신 것과 같은 기타 라이브러리를 사용하는 것은 허용되지 않습니다. 채점 기준 역시 Redux에 맞춰져 있는 상태입니다.

팀 프로젝트에서는 React와 Django를 사용한다는 전제 하에 기타 라이브러리를 무엇이든 자유롭게 사용하실 수 있습니다.

**Comment by promet99** [comment]
넵 감사합니다

**Comment by ddongminstar** [comment]
Redux persist, Redux toolkit과 같은 redux 관련 라이브러리는 사용이 가능할까요?

**Comment by kooyunmo** [comment]
실습 자료에 나와 있는 `yarn install [패키지]`로 설치하는 패키지들 외에 새로운 3rd party 라이브러리를 yarn install 하는 것은 허용되지 않습니다. 다만 실습 자료에 있는 패키지들을 활용하는 선에서 구현을 다르게 하는 것은 허용됩니다.
